worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;

    # =========================================================================
    # VIAGENSLABS (ATIVO - Porta 80)
    # =========================================================================
    server {
        listen       80;
        server_name  localhost;

        # Define que o Nginx servir? os arquivos est?ticos da pasta frontend
        root         C:\Projetos\viagens_labs\frontend;
        index        index.html;

        # Tudo que bater na raiz tenta achar o arquivo HTML est?tico primeiro
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Tudo que come?ar com /api/ ou /docs/ ou /openapi.json vai para o FastAPI (Python)
        location ~ ^/(api|docs|redoc|openapi.json) {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
